-- Apply RLS to all tables
ALTER TABLE "Mentee" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Mentor" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserSelection" ENABLE ROW LEVEL SECURITY;