AWSTemplateFormatVersion: '2010-09-09'
Transform:
  - AWS::Serverless-2016-10-31
Description: Insights Stack

Parameters:
  Stage:
    Type: String
    AllowedValues:
      - dev
      - test
      - prod
  AssistantHash:
    Type: String

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 30
    Architectures:
      - x86_64

Metadata: &esbuild_props
  Minify: true
  Target: 'es2020'
  External:
    - 'utils/*'
    - 'types/*'
  Sourcemap: true

Resources:
  InsightsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'*'"
        AllowMethods: "'*'"

  LambdaDefaultPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: 'arn:aws:logs:*:*:*'

  LambdaDefaultRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Ref LambdaDefaultPolicy

  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: SharedLayer
      ContentUri: layer/
      CompatibleRuntimes:
        - nodejs18.x
      Description: A layer with utils and types
    Metadata:
     BuildMethod: makefile

  GetInsightsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/insights/
      Handler: get-insights-handler.lambdaHandler
      Layers:
        - !Ref SharedLayer
      Role: !GetAtt LambdaDefaultRole.Arn
      Timeout: 60
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        <<: *esbuild_props
        EntryPoints:
          - get-insights-handler.ts

Outputs:
  API:
    Description: 'API Gateway endpoint URL for /getInsights'
    Value: !Sub 'https://${InsightsApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/'
